language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "install docker images"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t udagram-reverseproxy/reverse-proxy .
  - docker tag reverse-proxy reverse-proxy:latest

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push simple-reverse-proxy
